theme: jekyll-theme-minimal
title: Climate Visuals
description: Latest versions of open access climate visuals by Professor Ed Hawkins. These graphics show different aspects of how the climate is changing and are all free to use with a CC-BY license. They will be updated as new data becomes available.
show_downloads: true
